### ISSUE TITLE
Is every model stampable by default?

### ISSUE THREAD

**Issue by saghaulor** [lowjoel/activerecord-userstamp#10]
It seems that every model is stampable by default. This would be odd as the whole point of the stampable method is to indicate which models should be stamped.

**Comment by lowjoel** [comment]
Yes, every model is stampable by default. I'm removing the need to make it explicit because my app would rather stamp every single model.

It will not create the stampable callbacks if there is no created_by/updated_by columns, hence the need for the connection when the model is loaded.

**Comment by lowjoel** [comment]
Do reopen this if this is a problem.
