### ISSUE TITLE
undefined method `userstamps' for #<ActiveRecord::ConnectionAdapters::PostgreSQL::Table:0x0055a86811eea8>

### ISSUE THREAD

**Issue by dinesh-pallapa** [lowjoel/activerecord-userstamp#15]
I am trying to replace  delynn userstamp with activerecord-userstamp .when I am trying to run migrations 
its aborting migrations 

  def change
    change_table :YYY do |t|
      **t.userstamps**
  end

**undefined method `userstamps' for #<ActiveRecord::ConnectionAdapters::PostgreSQL::Table:0x0055a86811eea8>**

**Comment by lowjoel** [comment]
Which version of Rails is this?

**Comment by dinesh-pallapa** [comment]
I am using rails 4.2.5

**Comment by dineshPallapa** [comment]
Activerecord-userstamp failed to load MigrationHelper while I am running migrations. I resolved this issue by Adding migration helper to my repo and make use of this helper method in my migration file.
helper/activerecorduserstamp.rb

    module activeRecorduserstamp

      module ActiveRecord::Userstamp::MigrationHelper
      extend ActiveSupport::Concern

       def userstamps(*args)
          config = ActiveRecord::Userstamp.config
          column(config.creator_attribute, :integer, *args)
          column(config.updater_attribute, :integer, *args)
          column(config.deleter_attribute, :integer, *args) if config.deleter_attribute.present?
       end
     end

      ActiveRecord::ConnectionAdapters::TableDefinition.class_eval do
        include ActiveRecord::Userstamp::MigrationHelper
     end
    end
In My migrations file i included the helper mehod as
db/migration/yyy.rd

    include activeRecorduserstamp
    class YYY < ActiveRecord::Migration
        def change
          change_table :YYY do |t|
          t.userstamps
       end

>After adding helper method to my migration file .Activerecord-Userstamp working great.

**Comment by sripriyesha** [comment]
I fixed it by adding this gem to my Gemfile:

```ruby
gem 'activerecord-userstamp', :github => 'CircleSD/activerecord-userstamp', :branch => 'rails-6'
```
