### ISSUE TITLE
Record does not get user stamped when using custom column names

### ISSUE THREAD

**Issue by bennyzr** [lowjoel/activerecord-userstamp#18]
I added a migration for the users table to the rails-devise-pundit repository and moved the userstamp class to the initializers folder so it gets loaded. I then changed the users role (after allowing this in the pundit policy) to see if the user id was saved which was not the case. 

It does work when not using customized column names.

I tried pushing my changes to your git repository and was denied permission.

**Comment by lowjoel** [comment]
Push the changes to your https://github.com/bennyzr/rails-devise-pundit repo, I'll pull it from there.

**Comment by lowjoel** [comment]
Note that changing stuff in the initialisers require rebooting the Rails server.

**Comment by bennyzr** [comment]
Done. Please pull and check it out.

**Comment by lowjoel** [comment]
I've got a fix, let me try to push it in a PR for you to have a shot.

**Comment by bennyzr** [comment]
I tested the branch and it looks good. Thank you.

I have one question, when adding userstamp columns to an existing table the created field will be populated with the id of the user who next updates the record. Is this behavior intentional? My issue is that it does not reflect an accurate record of who created the record. I'd appreciate your thoughts on the matter.

**Comment by lowjoel** [comment]
An alternative would be to leave it null -- at that point there's not much that can be done. What do you propose?

**Comment by lowjoel** [comment]
Maybe open another issue for that, I'll close #19 first.
