### ISSUE TITLE
Can't verify CSRF token authenticity

### ISSUE THREAD

**Issue by bennyzr** [lowjoel/activerecord-userstamp#23]
After upgrading to Rails 5.1.2 I can't login and am getting a message "Can't verify CSRF token authenticity" when set_stamper is called in the method below in the ActiveRecord::Userstamp::ControllerAdditions module. 

    def with_stamper
      set_stamper
    byebug
      yield
    ensure
      reset_stamper
    end

The problem seems to be that when set_stamper calls current_user

     ActiveRecord::Userstamp.config.default_stamper_class.stamper = current_user

Warden starts the authentication process which causes `valid_authenticity_token?(session, token)` to fail.

Adding `unless self.class == Users::SessionsController` to the assignment solves the problem.

    ActiveRecord::Userstamp.config.default_stamper_class.stamper = current_user unless self.class == Users::SessionsController

Placing `skip_around_action :with_stamper` in the SessionsController also solves the problem.

Can you suggest a more elegant way to solve this?

**Comment by lowjoel** [comment]
@bennyzr: Try going to `ApplicationController`, and specify `protect_from_forgery with: __your_application_value__, prepend: true`

The CSRF handler needs to run before Userstamp does. I'll add it to the readme.
