### ISSUE TITLE
Fixnum is deprecated warning

### ISSUE THREAD

**Issue by noctivityinc** [lowjoel/activerecord-userstamp#26]
Anyone know how to deal with this warning when using userstamp?

`gems/ruby-2.4.1@dmvcs/gems/activerecord-userstamp-3.0.4/lib/active_record/userstamp/utilities.rb:52: warning: constant ::Fixnum is deprecated`

**Comment by lowjoel** [comment]
This will be fixed in the next release. If it affects you, you can point to master and use that now.
