### ISSUE TITLE
Publish release v3.0.5

### ISSUE THREAD

**Issue by mgrunberg** [lowjoel/activerecord-userstamp#28]
I realized that version 3.0.5 is not on RubyGems. Is there any plans to release it? 
I would like to use the gem with rails 5 without including it using git url.

Thanks

**Comment by lowjoel** [comment]
Sorry, there's some regressions that I'd like to fix before releasing another version. Thanks for your understanding.



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by mgrunberg** [comment]
Good to know. Thanks for your kick response
