### ISSUE TITLE
make deleter relation optional

### ISSUE THREAD

**Issue by mgrunberg** [lowjoel/activerecord-userstamp#29]
I'm working with Rails 5 and the belongs_to association is required by default. So new record validates that deleter exists.

The current workaround is to pass `optional: true` to `stamper` method and add the `presence` validation for creator & updater. Like this:

```
class SomeClass < ApplicationRecord
   stampable optional: true

   validates :creator, :updater, presence: true
end
```

**Comment by lowjoel** [comment]
Fixed in master, thanks!
