### ISSUE TITLE
stamp with non-id field?

### ISSUE THREAD

**Issue by reger** [lowjoel/activerecord-userstamp#3]
Is there a way to stamp with a different field on the User than id, email for instance?

**Comment by lowjoel** [comment]
I would imagine that you could store a reference to an email record, but I don't think this should explicitly support storing a string. I would try to reduce duplication in the database, so referencing an email record (as the stamper) would be what I'd do here.

**Comment by reger** [comment]
Not sure what you mean by reference an email record. I have a User model with an email field. I want to stamp Posts (for example), but don't want to have the id of the user in the created_by, updated_by fields, I'd rather have the user's email there.

**Comment by reger** [comment]
Are you saying that in this comment from Stampable, that "name" is not a simple string field on Person, it's an association, like `has_one` or something?

```
# This method customizes how the gem functions. For example:
#
#   class Post < ActiveRecord::Base
#     stampable stamper_class_name: Person.name,
#               with_deleted:       true
#   end
#
# The method will set up all the associations. Extra arguments (like +:with_deleted+) will be
# propagated to the associations.
```

**Comment by reger** [comment]
`name` on a class called `Person` is what made the comment confusing, but I get it now. It looks like I can't do what I want with the current gem

**Comment by lowjoel** [comment]
The `name` of a class is a string containing the name of the class.

If you wanted to accomplish this, you can make emails an explicit model and use that as a stamper. Beyond that, I think you'd have to roll your own.

**Comment by reger** [comment]
Yeah, I figured out the `name` thing. It being on `Person` had me reading it as `person.name` meaning it was the name of a person "bob", not the class name :) Thanks.
