### ISSUE TITLE
Avoid userstamp on rails task

### ISSUE THREAD

**Issue by Nittarab** [lowjoel/activerecord-userstamp#31]
Hi, I'm using rails task to get data from other DB. In my i have a tag table:
```
create_table :tags do |t|
      t.string :name, unique: true
      t.timestamps
      t.userstamps
    end
```

I need to create some tag in task and I'll hope to use this function:

`Tag.find_or_create_by(name: "sada")`

How can I avoid the userstamp validation ?

**Comment by GianDigia** [comment]
You have two ways to achieve this:

```
TASK_ID = some_user.id

Tag.where(name: "foo").first_or_create! do |tag|
  tag.creator_id = TASK_ID
  tag.updater_id = TASK_ID
end
```

or

```
User.stamper = some_user
Tag.find_or_create_by!(name: "foo")
```
