### ISSUE TITLE
Can't start my application after adding this gem

### ISSUE THREAD

**Issue by bluengreen** [lowjoel/activerecord-userstamp#4]
After adding to my gem file it gives me this error on rails s

```
/Users/phillip.novess/.rvm/gems/ruby-2.2.3@global/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:566:in `retrieve_connection': No connection pool for Attachinary::File (ActiveRecord::ConnectionNotEstablished)
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@global/gems/activerecord-4.2.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@global/gems/activerecord-4.2.1/lib/active_record/connection_handling.rb:87:in `connection'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@global/gems/activerecord-4.2.1/lib/active_record/attributes.rb:93:in `columns'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@global/gems/activerecord-4.2.1/lib/active_record/model_schema.rb:260:in `column_names'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@mathews/gems/activerecord-userstamp-3.0.4/lib/active_record/userstamp/utilities.rb:31:in `available_association_columns'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@mathews/gems/activerecord-userstamp-3.0.4/lib/active_record/userstamp/stampable.rb:75:in `add_userstamp_associations'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@mathews/gems/activerecord-userstamp-3.0.4/lib/active_record/userstamp/stampable.rb:26:in `block in inherited'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@mathews/gems/activerecord-userstamp-3.0.4/lib/active_record/userstamp/stampable.rb:25:in `class_eval'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@mathews/gems/activerecord-userstamp-3.0.4/lib/active_record/userstamp/stampable.rb:25:in `inherited'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@mathews/bundler/gems/attachinary-aafd0fd4f2b6/lib/attachinary/orm/active_record/file.rb:2:in `<module:Attachinary>'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@mathews/bundler/gems/attachinary-aafd0fd4f2b6/lib/attachinary/orm/active_record/file.rb:1:in `<top (required)>'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@mathews/bundler/gems/attachinary-aafd0fd4f2b6/lib/attachinary/orm/active_record.rb:4:in `require_relative'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@mathews/bundler/gems/attachinary-aafd0fd4f2b6/lib/attachinary/orm/active_record.rb:4:in `<top (required)>'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@global/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@global/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@global/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@global/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
    from /Users/phillip.novess/Projects/mathews/config/application.rb:9:in `<top (required)>'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@global/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:78:in `require'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@global/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:78:in `block in server'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@global/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@global/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `server'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@global/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@global/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
    from /Users/phillip.novess/Projects/mathews/bin/rails:9:in `require'
    from /Users/phillip.novess/Projects/mathews/bin/rails:9:in `<top (required)>'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@global/gems/spring-1.5.0/lib/spring/client/rails.rb:28:in `load'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@global/gems/spring-1.5.0/lib/spring/client/rails.rb:28:in `call'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@global/gems/spring-1.5.0/lib/spring/client/command.rb:7:in `call'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@global/gems/spring-1.5.0/lib/spring/client.rb:28:in `run'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@global/gems/spring-1.5.0/bin/spring:49:in `<top (required)>'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@global/gems/spring-1.5.0/lib/spring/binstub.rb:11:in `load'
    from /Users/phillip.novess/.rvm/gems/ruby-2.2.3@global/gems/spring-1.5.0/lib/spring/binstub.rb:11:in `<top (required)>'
    from /Users/phillip.novess/Projects/mathews/bin/spring:13:in `require'
    from /Users/phillip.novess/Projects/mathews/bin/spring:13:in `<top (required)>'
    from bin/rails:3:in `load'
    from bin/rails:3:in `<main>'
```

**Comment by lowjoel** [comment]
Looks like Attachinary is declaring a model before the AR connection is established. This creates problems for the automatic userstamp column inference, since that hook is run when a class is inherited.

I believe there's something that can be done, let me think about it.

**Comment by lowjoel** [comment]
Can you try modifying lib/active_record/userstamp/stampable.rb:75: `add_userstamp_associations` to return an empty array if a ConnectionNotEstablished is raised?

See if that fixes it.

**Comment by oneiros** [comment]
I think I am experiencing the same problem, except it is not triggered by Attachinary, which I do not use, but by the AR i18n backend.

The modification you proposed does indeed make the app boot up again without errors, but it also keeps the creator/updater/deleter associations from being set :frowning:

Have you had time to think about this some more?

I currently struggle with finding a solution and wonder if setting up these relationships automagically is even possible. And at least for me it is not necessary: Coming from the original userstamp plugin I already have a call to `stampable` in alle the models I want to use it in anyway.

I will think about this some more, but I would love to read other opinions as well.

**Comment by lowjoel** [comment]
I rather these things to be as magical as possible, because I don't want to run the risk of forgetting a declaration. I'm kind of tied up with other things -- I'd like to hear other opinions, but I'm not sure if I can currently work on any of it.

**Comment by oneiros** [comment]
> The modification you proposed does indeed make the app boot up again without errors, but it also keeps the creator/updater/deleter associations from being set :frowning:

Actually this is not true. The associations will also be set with a call to `stampable`, which is exactly the kind of solution I was looking for. The associations not being there was an actual bug in the application code I was looking at.

So, simply returning from `add_userstamp_associations` when there is no connection yet might actually be a valid workaround. Of course with the caveat that you will need to use `stampable` in all models that you want stamped.

BTW, you can query `ActiveRecord::Base.connected?` to check if a connection has been established. No need to rescue from an exception.

Sadly, activerecord-userstamp will still not work for me, even with this change in place. My test suite fails in seemingly unrelated places (including a weird postgresql error I have never seen before).

Sorry, I cannot be of more help right now, as I found that the insphire fork of the original userstamp plugin seems to work flawlessly in my case.

I would still be happy to try out any possible fixes that arise for this issue, though.

**Comment by lowjoel** [comment]
@oneiros can you open a separate issue for those Postgresql errors? I've made changes to the gem testing against Coursemology/coursemology2, but I don't remember needing to change anything to fix spec breakages.

I did however get bitten by Userstamp being a little too eager to declare the created_by and updated_by belongs_to attributes, but that's about it.

**Comment by lowjoel** [comment]
@bluengreen @oneiros Can you have a go at the PR in #12 and see if that helps? Thanks.
